language: java

arch:
    - amd64
    - arm64

jdk:
- openjdk8

install:
- apt-get install -y maven
- mvn clean install -B -V

script:
- sh ./check_format.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
