language: java

arch:
    - amd64
    - arm64

jdk:
- openjdk8

install:
- if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
    sudo apt-get install -y maven openjdk-8-jdk;
  fi
- mvn clean install -B -V

script:
- sh ./check_format.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
