language: java

arch:
    - amd64
    - arm64

jdk:
- openjdk8

install:
- sudo apt-get install -y maven openjdk-8-jdk
- mvn clean install -B -V

script:
- sh ./check_format.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
